# Generated by Django 4.0 on 2022-06-10 12:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checktime',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 12, 36, 34, 773371)),
        ),
    ]
